INSERT INTO locations (country, province, city, postal_code) VALUES ('Canada', 'Ontario', 'Mississauga', 'L4E 0G2');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Cookshire-Eaton', 'M4C');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Lachute', 'J8H');
insert into locations (country, province, city, postal_code) values ('Canada', 'Newfoundland and Labrador', 'Bonavista', 'E8M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Repentigny', 'J6V');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Kimberley', 'V1A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Dalmeny', 'M4P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Bridgewater', 'B4V');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Nelson', 'V1L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Sarnia', 'N7V');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'La Tuque', 'G9X');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Owen Sound', 'N4K');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Asbestos', 'J1T');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Lillooet', 'H9G');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'North Vancouver', 'V7Y');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Mattawa', 'V5M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Arnprior', 'K7S');
insert into locations (country, province, city, postal_code) values ('Canada', 'Prince Edward Island', 'Alberton', 'P7K');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Saskatoon', 'S7W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Newfoundland and Labrador', 'Carbonear', 'A1Y');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Martensville', 'L3R');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Hope', 'V7R');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Kamloops', 'H9P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'North Battleford', 'S9A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Norfolk County', 'T0C');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Lacombe', 'T4L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Canmore', 'T1W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Kamsack', 'R2J');
insert into locations (country, province, city, postal_code) values ('Canada', 'Manitoba', 'Virden', 'J5V');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Antigonish', 'B2G');
insert into locations (country, province, city, postal_code) values ('Canada', 'Manitoba', 'Virden', 'J5V');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Estevan', 'S4A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Millet', 'T8C');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Saint-Ambroise', 'G7P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Danville', 'J0A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Wolfville', 'B4P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Hanover', 'N4N');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Bedford', 'J6W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Saskatoon', 'S7W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Melfort', 'B3H');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Drummondville', 'J2E');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Clarence-Rockland', 'K4K');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Nelson', 'V1L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Pilot Butte', 'N8M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'North Bay', 'P1A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Chester', 'N9A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Greenwood', 'E6J');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Macklin', 'B0K');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Lavaltrie', 'J5T');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Maple Ridge', 'V2X');
insert into locations (country, province, city, postal_code) values ('Canada', 'Manitoba', 'Niverville', 'T5G');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Edson', 'T7E');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'La Ronge', 'J9P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Manitoba', 'Boissevain', 'G7S');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Hudson', 'J0N');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Mont-Laurier', 'J9L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Rocky Mountain House', 'T4T');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Fort Erie', 'L2A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Martensville', 'L3R');
insert into locations (country, province, city, postal_code) values ('Canada', 'Prince Edward Island', 'Alberton', 'P7K');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Maskinongé', 'T7A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Amos', 'J9T');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Petawawa', 'K8H');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Rayside-Balfour', 'G9T');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Parry Sound', 'P2A');
insert into locations (country, province, city, postal_code) values ('Canada', 'Manitoba', 'Minnedosa', 'N3E');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Taber', 'T1G');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Port Moody', 'V3H');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Saint-Jérôme', 'J7Z');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Alma', 'N6J');
insert into locations (country, province, city, postal_code) values ('Canada', 'Prince Edward Island', 'Cornwall', 'L4E');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'South River', 'P3Y');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Carleton-sur-Mer', 'P0T');
insert into locations (country, province, city, postal_code) values ('Canada', 'British Columbia', 'Revelstoke', 'H9K');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Vegreville', 'T9C');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Fort Macleod', 'V6S');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'South River', 'P3Y');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Grimshaw', 'N4W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Ajax', 'L1Z');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Mississauga', 'L5W');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Collingwood', 'L9Y');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Barraute', 'P0M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Watrous', 'L9T');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Orillia', 'L3V');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Mattawa', 'V5M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Beauharnois', 'J6N');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Peterborough', 'K9H');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Rayside-Balfour', 'G9T');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Maple Creek', 'P3L');
insert into locations (country, province, city, postal_code) values ('Canada', 'New Brunswick', 'Shediac', 'E4P');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Lacombe', 'T4L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Nova Scotia', 'Pictou', 'M1M');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Delson', 'J5B');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Gananoque', 'K7G');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'L''Île-Perrot', 'H9X');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Calgary', 'T3S');
insert into locations (country, province, city, postal_code) values ('Canada', 'Québec', 'Chambly', 'J3L');
insert into locations (country, province, city, postal_code) values ('Canada', 'Saskatchewan', 'Gravelbourg', 'G8V');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Devon', 'T9G');
insert into locations (country, province, city, postal_code) values ('Canada', 'Alberta', 'Grande Cache', 'N2Z');
insert into locations (country, province, city, postal_code) values ('Canada', 'Ontario', 'Newmarket', 'L9N');

